# AgentBootstrap.py
# Three-agent pipeline with OpenTelemetry spans on every step.

import os
import json
import re
from dotenv import load_dotenv

from opentelemetry import trace

from langchain_openai import AzureChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

import SqlServerBootstrap

load_dotenv()

# Global tracer -- picks up the provider set in OpenTelemetryBootstrap.setup()
tracer = trace.get_tracer("AgentBootstrap", "1.0.0")

# -----------------------------
# 1. Azure OpenAI Model
# -----------------------------
model = AzureChatOpenAI(
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
    azure_deployment=os.getenv("AZURE_OPENAI_DEPLOYMENT"),
    temperature=0,
)

# -----------------------------
# 2. SQL Client
# -----------------------------
cfg = SqlServerBootstrap.SqlExecutionConfig(
    server=os.getenv("SQL_SERVER", "localhost"),
    database=os.getenv("SQL_DATABASE", "TestDB"),
)

sql_client = SqlServerBootstrap.SqlServerTelemetryExecutor(cfg)

# -----------------------------
# 3. System Prompts
# -----------------------------
GENERATE_SQL_SYSTEM = """
You are GenerateSqlAgent, an expert SQL Server T-SQL generator.

Primary responsibility:
- Analyze the user request.
- Classify it as NON_SEMANTIC or SEMANTIC.
- Generate exactly ONE safe, read-only T-SQL statement.

Output contract:
- Output MUST be valid JSON.
- Exactly two keys only:
  - classification: NON_SEMANTIC or SEMANTIC
  - sql: the T-SQL to execute

SQL restrictions:
- Allowed:
  - One SELECT statement
  - One EXEC dbo.usp_find_similar_products_by_embedding call
- Forbidden:
  - INSERT, UPDATE, DELETE, MERGE
  - CREATE, ALTER, DROP, TRUNCATE
  - Multiple statements
  - Comments or natural language text

If the request is ambiguous:
- Default to NON_SEMANTIC.

Schema:
- dbo.products(productid, name, category, description, image_data)
- dbo.product_review_summary(productid, abstractive_summary, sentiment_label, positive_score, neutral_score, negative_score)
- dbo.products_vector(productid, embedding_ranker)

Semantic stored procedure (SEMANTIC only):
EXEC dbo.usp_find_similar_products_by_embedding
  @query_text = N'<user intent>',
  @top_n = <number>,
  @model_name = N'MyAzureOpenAIModel';
"""

EXECUTE_SQL_SYSTEM = """
You are ExecuteSqlAgent.

Primary responsibility:
- Receive SQL generated by GenerateSqlAgent.
- Validate safety.
- Execute the SQL exactly as received.

Safety rules:
- Refuse if SQL contains: INSERT, UPDATE, DELETE, MERGE, CREATE, ALTER, DROP, TRUNCATE, GRANT, REVOKE

Allowed execution:
- SELECT statements
- EXEC dbo.usp_find_similar_products_by_embedding only

Output contract:
- If unsafe:   EXECUTION_ERROR: UNSAFE_SQL
- If execution fails: EXECUTION_ERROR: <error detail>
- If successful: EXECUTION_RESULT: <raw data>
"""

DATA_ANALYST_SYSTEM = """
You are DataAnalystAgent, a senior data analyst with strong business communication skills.

Primary responsibility:
- Analyze the exact output returned by ExecuteSqlAgent.
- Answer very concisely the original user question in a human, natural tone.

Rules:
- Base your reasoning ONLY on the execution output.
- Do NOT invent or assume missing data.
- Do NOT mention agents, tools, chains, prompts, or internal steps.

If the output is successful:
- Briefly explain what the data shows.
- Use bullet points to list results.

If the output is empty:
- Say clearly that no records were found.

If the output is an error:
- Explain the issue in simple terms.

Output format:
- One short introductory sentence.
- Then 2 to 8 concise bullet points.
"""

# -----------------------------
# 4. Chains
# -----------------------------
generate_prompt = ChatPromptTemplate.from_messages([
    ("system", GENERATE_SQL_SYSTEM),
    ("human", "{user_query}")
])

execute_prompt = ChatPromptTemplate.from_messages([
    ("system", EXECUTE_SQL_SYSTEM),
    ("human", "{sql_payload}")
])

data_analyst_prompt = ChatPromptTemplate.from_messages([
    ("system", DATA_ANALYST_SYSTEM),
    ("human",
     "User question:\n{user_query}\n\n"
     "Classification:\n{classification}\n\n"
     "SQL executed:\n{sql}\n\n"
     "ExecuteSqlAgent output:\n{execution_output}")
])

generate_chain = generate_prompt | model | StrOutputParser()
execute_chain  = execute_prompt  | model | StrOutputParser()
data_analyst_chain = data_analyst_prompt | model | StrOutputParser()

# -----------------------------
# 5. SQL Safety Validation
# -----------------------------
FORBIDDEN = re.compile(
    r"\b(INSERT|UPDATE|DELETE|MERGE|DROP|TRUNCATE|ALTER|CREATE|GRANT|REVOKE)\b",
    re.IGNORECASE
)

ALLOWED_SEMANTIC_EXEC = re.compile(
    r"^\s*EXEC\s+dbo\.usp_find_similar_products_by_embedding\b",
    re.IGNORECASE
)


def is_safe_sql(sql: str) -> bool:
    """Return True only when the SQL is a safe SELECT or an allowed EXEC."""
    if not sql or not sql.strip():
        return False
    stripped = sql.strip()
    if ALLOWED_SEMANTIC_EXEC.match(stripped):
        return True
    if FORBIDDEN.search(stripped):
        return False
    if stripped.upper().startswith("SELECT"):
        return True
    return False

# -----------------------------
# 6. ExecuteSqlAgent (Python-enforced)
# -----------------------------
def execute_sql_agent(sql: str) -> str:
    """Validates safety, executes safe SQL, returns strict format."""
    with tracer.start_as_current_span("execute_sql_agent.safety_check") as span:
        span.set_attribute("sql.statement", sql)
        safe = is_safe_sql(sql)
        span.set_attribute("sql.is_safe", safe)
        if not safe:
            span.set_attribute("sql.result", "UNSAFE_SQL")
            return "EXECUTION_ERROR: UNSAFE_SQL"

    with tracer.start_as_current_span("execute_sql_agent.run_query") as span:
        span.set_attribute("sql.statement", sql)
        try:
            result = sql_client.execute_sql(sql)
            span.set_attribute("sql.result", result[:500])
            return f"EXECUTION_RESULT:\n{result}"
        except Exception as exc:
            span.set_attribute("sql.error", str(exc))
            return f"EXECUTION_ERROR: {exc}"

# -----------------------------
# 7. Orchestrator (3 agents)
# -----------------------------
def run_three_agent_pipeline(user_query: str) -> dict:
    """
    Runs GenerateSqlAgent -> ExecuteSqlAgent -> DataAnalystAgent.
    Each step is wrapped in an OpenTelemetry span.
    """
    with tracer.start_as_current_span("pipeline.full") as root_span:
        root_span.set_attribute("user.query", user_query)

        # --- Agent 1: Generate SQL ---
        with tracer.start_as_current_span("agent.generate_sql") as span:
            raw = generate_chain.invoke({"user_query": user_query}).strip()
            span.set_attribute("agent.raw_output", raw[:500])
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError:
                match = re.search(r"\{.*\}", raw, re.DOTALL)
                if match:
                    parsed = json.loads(match.group())
                else:
                    span.set_attribute("agent.error", "JSON parse failure")
                    return {
                        "classification": "ERROR",
                        "sql": "",
                        "execute_agent_output": f"GENERATION_ERROR: Could not parse: {raw}",
                        "final_answer": "Sorry, I could not generate a valid SQL query for your question."
                    }

            classification = parsed.get("classification", "UNKNOWN")
            sql = parsed.get("sql", "")
            span.set_attribute("agent.classification", classification)
            span.set_attribute("agent.sql", sql)

        # --- Agent 2: Execute SQL ---
        with tracer.start_as_current_span("agent.execute_sql") as span:
            exec_output = execute_sql_agent(sql)
            span.set_attribute("agent.output", exec_output[:500])

        # --- Agent 3: Data Analyst ---
        with tracer.start_as_current_span("agent.data_analyst") as span:
            final_answer = data_analyst_chain.invoke({
                "user_query": user_query,
                "classification": classification,
                "sql": sql,
                "execution_output": exec_output,
            })
            span.set_attribute("agent.final_answer", final_answer[:500])

        return {
            "classification": classification,
            "sql": sql,
            "execute_agent_output": exec_output,
            "final_answer": final_answer,
        }

# -----------------------------
# 8. Run (standalone test)
# -----------------------------
if __name__ == "__main__":
    query = "Show me the top 5 products with the highest positive sentiment score."
    out = run_three_agent_pipeline(query)
    print(f"\nClassification : {out['classification']}")
    print(f"SQL            : {out['sql']}")
    print(f"Exec Output    : {out['execute_agent_output'][:300]}")
    print(f"\n--- Final Answer ---\n{out['final_answer']}")
